# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python_mysql:
    build: ./bobo
    volumes:
      - ./dodo/dodo.py:/usr/src/app/dodo.py